name: CI

on:
  pull_request:
  push:
    branches:
      - main
      
      
jobs:
  tests:
    name: Test ${{matrix.runs_on}}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix: 
        runs-on: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install package
        run: python -m pip install .[test]

      - name: Test package
        run: python -m pytest
